# Generated by Django 6.0.2 on 2026-03-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_cinemahall_movie_moviesession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moviesession",
            old_name="cinemahall",
            new_name="cinema_hall",
        ),
    ]
